# fly.toml app configuration file generated for reach-chat on 2023-06-12T21:46:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reach-chat"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
